### ISSUE TITLE
extract_text.py texts are messed up?

### ISSUE THREAD

**Issue by ghost** [jasonlfunk/ocr-text-extraction#1]
This is a great effort and some tweaking it could be very useful for tesseract OCR.

the problem right now is that resulting text seems almost like it's from an withering ancient book. For example "O" looks almost like "U".

the best way I can put it is texts look almost dirty.

what variables or configs can I alter to retain the clean cut text like shown in the answer at 

http://stackoverflow.com/questions/11678542/image-processing-for-ocr-with-leptonica-inverse-color-text

**Comment by jasonlfunk** [comment]
Do you have an example image I can see? I admit that it isn't the best. I think the OpenCV implementation of bounding boxes is the current problem. The algorithm is designed to not need to tune any parameters.

**Comment by ghost** [comment]
I will post up the images tonight.
