### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Sanjeeth8733** [jasonlfunk/ocr-text-extraction#12]
<ipython-input-53-8ff0275bfe7e> in extract_bv(image)
     22     ret,f6 = cv2.threshold(f5,15,255,cv2.THRESH_BINARY)
     23     mask = np.ones(f5.shape[:2], dtype="uint8") * 255
---> 24     image, contours, hierarchy = cv2.findContours(f6.copy() ,cv2.RETR_LIST ,cv2.CHAIN_APPROX_SIMPLE)
     25     for cnt in contours:
     26         if cv2.contourArea(cnt) <= 200:

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by maky-hnou** [comment]
@Sanjeeth8733 , depending on your OpenCV version, use `contours, hierarchy = cv.findContours(f6.copy() ,cv2.RETR_LIST ,cv2.CHAIN_APPROX_SIMPLE)`  or ` image, contours, hierarchy = cv2.findContours(f6.copy() ,cv2.RETR_LIST ,cv2.CHAIN_APPROX_SIMPLE)`  
Check [OpenCV documentation](https://docs.opencv.org/4.1.2/d4/d73/tutorial_py_contours_begin.html) for more details

**Comment by Sanjeeth8733** [comment]
> @Sanjeeth8733 , depending on your OpenCV version, use `contours, hierarchy = cv.findContours(f6.copy() ,cv2.RETR_LIST ,cv2.CHAIN_APPROX_SIMPLE)` or ` image, contours, hierarchy = cv2.findContours(f6.copy() ,cv2.RETR_LIST ,cv2.CHAIN_APPROX_SIMPLE)`
> Check [OpenCV documentation](https://docs.opencv.org/4.1.2/d4/d73/tutorial_py_contours_begin.html) for more details

thank you, it worked.
